sudo: required
language: python
cache: pip
python:
- 3.6
- 3.7
- 3.8
before_install:
- pip install -r dev_requirements.txt
script:
- python setup.py develop
- python setup.py test
- python setup.py sdist bdist bdist_wheel
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: __token__
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
  password:
    secure: igGDkKL4t1d3VF1W3H41u91uGM2VH8NrXJqNOn0TzKIAI4GZUk/z3G6QFFFr5Ubx/lbmpPekX7j00TVAHqGKZfWD1qvnmFSR2LkLMl7BYkDc9nS5ka+hmmv9ywopZnO3TDfuJdiIL+KxVO//yzUPBCdRe0EUE7Gr8RKup5RqTZLtD+IOrc+WVIYvNj7if8dudDPrdcpDYZQRcnMKZXdOSUstzsfdUR1nJKvaHH+FKXGRNdiiNH8l/xmy5g0S8DINDebrkfgNTHNrOzH/e9kmPfn2IcczaMhpT92MYKtfIjqqbleYP3QEmpezgRhviHoMMYqJq9xNPa/M5zgm7YdbmbNPQFxRiGE0MRIKs/u5QkjCD8QnWHmqBbpEjgeqTG0HLu2nvXKEckzB/m8vUV8TVZQYZiKvdzjS03FFpJBsaitXQEeqRQFAuU1j8ZcM0X9qQy81bbApvT+gV8NXSbPi8iOcXywQC7prPGYW/r+bjzRSQgFpv/bIFVw7DM/suX8g8ibpba4HEbiWgD1a9kpDYQvC3XOUQzlvajP8CCLJw8oGFew+4rD1v7QJfMhtNpRW2geQbhKQj/IkjGtoSVpgwfpykTUo2b4Vi/pa+feEpzyScmhV5FV5ysSUqSEg2HhDrxoho1GswwFnBMQG878QmqwTrEd+Gy1AzOGHYHpqgaY=
